/**
 * Codegen: derive TypeScript types from the canonical JSON Schemas.
 * Schemas are the source of truth (ADR-0003); this writes `src/generated/` which is git-ignored
 * and regenerated by `pnpm codegen`. Run before typecheck/test.
 */
import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");
const outDir = join(here, "..", "src", "generated");

async function main(): Promise<void> {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const files = (await readdir(schemasDir)).filter((f) => f.endsWith(".schema.json")).sort();
  const exportLines: string[] = [
    "// AUTO-GENERATED by scripts/codegen.ts from schemas/*.schema.json. Do not edit.",
    "",
  ];

  for (const file of files) {
    const raw = await readFile(join(schemasDir, file), "utf8");
    const schema = JSON.parse(raw) as { title?: string };
    const base = file.replace(/\.schema\.json$/, "");
    const typeName = schema.title ?? base;
    const ts = await compile(schema as Parameters<typeof compile>[0], typeName, {
      bannerComment: `/* AUTO-GENERATED from schemas/${file}. Do not edit by hand. */`,
      additionalProperties: false,
      style: { singleQuote: false, printWidth: 100 },
    });
    await writeFile(join(outDir, `${base}.ts`), ts, "utf8");
    exportLines.push(`export * from "./${base}";`);
  }

  await writeFile(join(outDir, "index.ts"), `${exportLines.join("\n")}\n`, "utf8");
  console.log(`codegen: generated ${files.length} type module(s) in src/generated/`);
}

main().catch((error: unknown) => {
  console.error("codegen failed:", error);
  process.exit(1);
});
