export {
  COGNITION_BLOCK_TYPES,
  createCognitionBlock,
  type BlockClassification,
  type BlockProvenance,
  type CognitionBlock,
  type CognitionBlockType,
  type CreateBlockContext,
  type CreateBlockInput,
} from "./blocks";
export {
  AgentContributionRuntime,
  contributionFromDispatch,
  type AgentContribution,
  type AgentContributionRuntimeDeps,
} from "./contribution";
export {
  MCCR_ELEMENT_TYPES,
  readMccr,
  type CognitiveFrame,
  type CognitiveFrameStatus,
  type FrameLayout,
  type FrameLayoutSlot,
  type FrameProvenance,
  type ImageDecisionRecord,
  type Mccr,
  type MccrDiagram,
  type MccrElement,
  type MccrElementContent,
  type MccrElementType,
  type MccrImageArtifact,
  type NarrationIntent,
  type NarrationScriptRecord,
  type NarrationScriptSegment,
  type StreamingFrameElementBuffer,
} from "./frames";
export {
  foldSurfaceEvents,
  type AgentPresence,
  type AgentPresenceState,
  type AgentReasoningRecord,
  type AgentWorkStatus,
  type AgentWorkTimingRecord,
  type DepthGateRecord,
  type DisagreementRecord,
  type FocusTargetType,
  type NarrationSegment,
  type NarrationVoice,
  type PrerequisiteDescentRecord,
  type ProjectionMode,
  type ResearchFrontierRecord,
  type ResumeCardRecord,
  type StreamingBlockBuffer,
  type SurfaceContributionRecord,
  type SurfaceFocus,
  type SurfaceRoutingRecord,
  type SurfaceState,
} from "./projection";
export {
  SHOT_KINDS,
  REDUCED_MOTION_REALIZATION,
  planShots,
  readShot,
  type SceneShot,
  type ShotKind,
  type ShotActor,
  type ShotSegment,
  type PlanShotsInput,
} from "./cinematography";
export {
  INTERACTION_GRAMMAR,
  interpretIntent,
  readExpressedIntent,
  type InteractionClass,
  type InteractionRouting,
  type InterpretedIntent,
  type ExpressedIntentRecord,
} from "./interaction";
export {
  DIRECTOR_STATES,
  decideDirective,
  inferAffect,
  readDirective,
  readAffectSignal,
  readAttentionBudget,
  readSceneOpened,
  readSceneDelta,
  type AffectSignalRecord,
  type AffectState,
  type AttentionBudgetRecord,
  type DirectiveRecord,
  type DirectiveScale,
  type DirectorSignals,
  type DirectorState,
  type SceneActor,
  type SceneDeltaRecord,
  type SceneLighting,
  type SceneRecord,
} from "./theater";
export {
  planSourceProjection,
  planSourceRender,
  readSourceBinding,
  readSourceHighlight,
  readSourceRegion,
  readSyncBinding,
  readViewportChange,
  readViewportPlan,
  type PlanSourceProjectionInput,
  type PlannedSourceProjection,
  type SourceBindingRecord,
  type FrontierEntryView,
  type FrontierOverlayView,
  type SourceEvidenceAnchorView,
  type SourceEvidenceProvider,
  type FusedSynthesisView,
  type SurfaceFrontierProvider,
  type SourceHighlightAmplitude,
  type SourceHighlightLifetime,
  type SourceHighlightRecord,
  type SourceHighlightRole,
  type SourceProvenanceClass,
  type SourceRegionView,
  type SourceSyncBinding,
  type SourceSyncBindingRecord,
  type SourceViewport,
  type SourceViewportChangeRecord,
  type SourceViewportPlanRecord,
  type ViewportChangeCause,
  type ViewportEmphasis,
  type SourceRenderDecision,
  type SourceRenderPlacement,
  type PlanSourceRenderInput,
} from "./source-projection";
export {
  planRepresentation,
  expertiseFromMastery,
  epistemicRoleFor,
  hierarchyFor,
  DENSITY_BUDGET,
  type EpistemicRole,
  type RepresentationHierarchy,
  type RepresentationElementPlan,
  type RepresentationDensity,
  type RepresentationPlan,
  type ExpertiseLevel,
  type RepresentationAdaptivity,
} from "./representation";
export { deriveEpisodes, currentEpisode, type Episode } from "./episodes";
export {
  structureExplanation,
  explanationSectionRole,
  coerceEpistemicRole,
  sectionsFromRoleTexts,
  EXPLANATION_ROLE_VOCAB_VERSION,
  type SemanticSection,
} from "./semantic-explanation";
export {
  NullMultimodalProvider,
  ProviderRegistry,
  surfaceProviderError,
  type ImageGenerationProvider,
  type LiveSessionHandle,
  type LiveSessionProvider,
  type MediaArtifact,
  type MediaGenerationRef,
  type MediaGenerationRequest,
  type MediaGenerator,
  type MediaModality,
  type MediaRequest,
  type MultimodalProvider,
  type ProviderDescriptor,
  type VideoGenerationProvider,
  type VoiceProvider,
} from "./providers";
export {
  SurfaceChoreographer,
  segmentNarration,
  collectNarrationTexts,
  type NarrateBlockInput,
  type NarrateInput,
  type NarrateScriptInput,
  type NarrateScriptSegmentInput,
  type PresenceInput,
  type SurfaceChoreographerDeps,
  type VoiceSynthesisRequest,
  type VoiceSynthesizer,
} from "./narration";
export { TextSurfaceRenderer, type SurfaceRenderer } from "./renderer";
export {
  SurfaceSession,
  type GovernedDispatcher,
  type SurfaceAskInput,
  type SurfaceAskResult,
  type SurfaceSessionDeps,
} from "./session";
export {
  SurfaceTimelineBuilder,
  type SurfaceTimelineBuilderDeps,
  type SurfaceTimelineInput,
  type SurfaceTimelineNode,
  type TimelineNodeStatus,
  type TimelineProjection,
} from "./timeline";
export { traceBlock, type BlockTrace } from "./trace";
